
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration

name: Continuos Integration

on:
    pull_request:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest
        environment:
            name: Dev
            url: 'rochadaniel15@gmail.com'
        steps:
            # https://github.com/marketplace/actions/checkout
            # Etapa que baixa uma cópia de seu repositório para execução corrente
            - name: Checkout
              uses: actions/checkout@v3
               
            # https://github.com/marketplace/actions/setup-java-jdk
            # Etapa de configuração do Java 11 JDK da Adoptium.
            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                java-version: 11
                distribuition: 'zulu'
                
            # https://github.com/marketplace/actions/setup-maven
            # Etapa de configuração do maven@3.8.2
            - name: Setup Maven
              uses: stCarolas/setup-maven@4.4
              with:
                maven-version: 3.8.2
                
            # Etapa de build e execução dos testes
            - name: Build and run tests
              run: mvn --batch-mode --update-snapshots verify
