
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration

name: Continuos Integration

on:
    pull_request:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest
#         environment:
#             name: Dev
#             url: 'rochadaniel15@gmail.com'
        steps:
            # https://github.com/marketplace/actions/checkout
            # Etapa que baixa uma cópia de seu repositório para execução corrente
            - name: Checkout
              uses: actions/checkout@v3
               
            # https://github.com/marketplace/actions/setup-java-jdk
            # Etapa de configuração do Java 11 JDK Zulu e Maven.
            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'zulu'
                cache: 'maven'
                
            # Etapa de build e execução dos testes
            - name: Build and run tests
              run: mvn clean install #--batch-mode --update-snapshots verify
